openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: delectus
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: mathew79@example.net
                password:
                  type: string
                  description: ''
                  example: '}C$!wj'
              required:
                - name
                - email
                - password
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: dherzog@example.org
                password:
                  type: string
                  description: ''
                  example: ducimus
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/client:
    post:
      summary: ''
      operationId: postApiClient
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/clients:
    get:
      summary: ''
      operationId: getApiClients
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/client/{id}':
    get:
      summary: ''
      operationId: getApiClientId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiClientId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the client.'
        example: dolorum
        required: true
        schema:
          type: string
  '/api/client/update/{id}':
    post:
      summary: ''
      operationId: postApiClientUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: ut
        required: true
        schema:
          type: string
  /api/fournissur:
    post:
      summary: ''
      operationId: postApiFournissur
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/fournissurs:
    get:
      summary: ''
      operationId: getApiFournissurs
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/fournissur/{id}':
    get:
      summary: ''
      operationId: getApiFournissurId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiFournissurId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the fournissur.'
        example: consectetur
        required: true
        schema:
          type: string
  '/api/fournissur/update/{id}':
    post:
      summary: ''
      operationId: postApiFournissurUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: quod
        required: true
        schema:
          type: string
  /api/categori:
    post:
      summary: ''
      operationId: postApiCategori
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/categories:
    get:
      summary: ''
      operationId: getApiCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/categori/{id}':
    get:
      summary: ''
      operationId: getApiCategoriId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiCategoriId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the categori.'
        example: consequuntur
        required: true
        schema:
          type: string
  '/api/categori/update/{id}':
    post:
      summary: ''
      operationId: postApiCategoriUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: aut
        required: true
        schema:
          type: string
  /api/product:
    post:
      summary: ''
      operationId: postApiProduct
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/product/{id}':
    get:
      summary: ''
      operationId: getApiProductId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: necessitatibus
        required: true
        schema:
          type: string
  '/api/product/update/{id}':
    post:
      summary: ''
      operationId: postApiProductUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: corporis
        required: true
        schema:
          type: string
  /api/facture:
    post:
      summary: ''
      operationId: postApiFacture
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/factures:
    get:
      summary: ''
      operationId: getApiFactures
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/facture/{id}':
    get:
      summary: ''
      operationId: getApiFactureId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiFactureId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the facture.'
        example: praesentium
        required: true
        schema:
          type: string
  '/api/facture/update/{id}':
    post:
      summary: ''
      operationId: postApiFactureUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: architecto
        required: true
        schema:
          type: string
  /api/Commende:
    post:
      summary: ''
      operationId: postApiCommende
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/Commendes:
    get:
      summary: ''
      operationId: getApiCommendes
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/Commende/{id}':
    get:
      summary: ''
      operationId: getApiCommendeId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiCommendeId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the Commende.'
        example: quia
        required: true
        schema:
          type: string
  '/api/Commende/update/{id}':
    post:
      summary: ''
      operationId: postApiCommendeUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: possimus
        required: true
        schema:
          type: string
  '/api/gererfournisseur/{id}':
    post:
      summary: ''
      operationId: postApiGererfournisseurId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the gererfournisseur.'
        example: odio
        required: true
        schema:
          type: string
  '/api/gererclient/{id}':
    post:
      summary: ''
      operationId: postApiGererclientId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the gererclient.'
        example: necessitatibus
        required: true
        schema:
          type: string
  '/api/gererpermission/{id}':
    post:
      summary: ''
      operationId: postApiGererpermissionId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the gererpermission.'
        example: consectetur
        required: true
        schema:
          type: string
  '/api/gererusrs/{id}':
    post:
      summary: ''
      operationId: postApiGererusrsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the gererusr.'
        example: optio
        required: true
        schema:
          type: string
  /api/users:
    get:
      summary: ''
      operationId: getApiUsers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/user/{id}':
    get:
      summary: ''
      operationId: getApiUserId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiUserId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: laboriosam
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
